index:
    path: /
    controller: App\Controller\DefaultController::index
## Tet Space
shoe-shop-2022:
  path: /shoe-shop/{code}
  controller: App\Controller\ShoeShopController::index
  defaults:
    code: ''
  methods: GET|POST
